[package]
name = "replication"
version = "0.1.0"
edition = "2021"

[dependencies]
tsdb-core = { path = "../tsdb-core" }
storage = { path = "../storage" }
serde = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }