[package]
name = "compression"
version = "0.1.0"
edition = "2021"

[dependencies]
tsdb-core = { path = "../tsdb-core" }
serde = { workspace = true }
thiserror = { workspace = true }
byteorder = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
criterion = { workspace = true }